#ifndef __VMS_ERROR_CODE__
#define __VMS_ERROR_CODE__

#define VMS_INVALID -1

#define VMS_SUCCESS 0

#define VMS_ERROR_BASE 1

#define PROCESS_CMD_EXCEPTION (VMS_ERROR_BASE+1)

#define VMS_NET_INIT_FAILED (VMS_ERROR_BASE+2)

#define USER_OR_PASSWORD_NULL (VMS_ERROR_BASE+3)

#define VMS_XML_PARSER_ERROR (VMS_ERROR_BASE+4)

#define VMS_INVALID_CMD_CODE (VMS_ERROR_BASE+5)

#define VMS_HOST_NOT_FOUND (VMS_ERROR_BASE+6)

#define CONNECTED_OR_CONNECTTING (VMS_ERROR_BASE+7)

#define FAILED_TO_CONNECT_SERVER (VMS_ERROR_BASE+8)

#define USER_IS_DISABLE (VMS_ERROR_BASE+9)

#define PSW_IS_INVALID (VMS_ERROR_BASE+10)

#define USER_NO_EXIST (VMS_ERROR_BASE+11)

#define XML_INVALID (VMS_ERROR_BASE+12)

#define VIDEO_IS_CLOSE (VMS_ERROR_BASE+13)

#define VIDEO_IS_OPENED (VMS_ERROR_BASE+14)

#define VMS_CLIENT_OFFLINE (VMS_ERROR_BASE+15)

#define VMS_RTSP_OPEN_FAILED (VMS_ERROR_BASE+16)

#define VMS_SNAPSHOT_FAILED (VMS_ERROR_BASE+17)

#define AUDIO_IS_CLOSE (VMS_ERROR_BASE+18)

#define AUDIO_IS_OPENED (VMS_ERROR_BASE+19)

#endif